// <auto-generated />
using System;
using CardDesigner.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CardDesigner.Data.Migrations
{
    [DbContext(typeof(CardDesignerDbContext))]
    [Migration("20220523190134_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("CardDesigner.Domain.Entities.CardDeck", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CharacterID");

                    b.ToTable("CardDeck");
                });

            modelBuilder.Entity("CardDesigner.Domain.Entities.Character", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("CardDesigner.Domain.Entities.CardDeck", b =>
                {
                    b.HasOne("CardDesigner.Domain.Entities.Character", null)
                        .WithMany("Decks")
                        .HasForeignKey("CharacterID");
                });

            modelBuilder.Entity("CardDesigner.Domain.Entities.Character", b =>
                {
                    b.Navigation("Decks");
                });
#pragma warning restore 612, 618
        }
    }
}
